### ISSUE TITLE
[Zephyr] Use Kconfig instead of CMake variables for configuration

### ISSUE THREAD

**Issue by SebastianBoe** [runtimeco/mcuboot#186]
Hi,

I'm not sure what the background for this code is:

```

> ########################
> # Configuration choices.
> ########################
> 
> # Set CONF_SIGNATURE_TYPE to determine the signature type used.
> # Currently, it should be set to either RSA or ECDSA_P256.
> #
> # To choose RSA (this is the default):
> #
> #     cmake -DCONF_SIGNATURE_TYPE=RSA [...]
> #
> # To use ECDSA_P256:
> #
> #     cmake -DCONF_SIGNATURE_TYPE=ECDSA_P256 [...]
> if (NOT DEFINED CONF_SIGNATURE_TYPE)
>   set(CONF_SIGNATURE_TYPE RSA)
> endif()
> 
```

but as a general rule it is preferable to use Kconfig rather than CMake variables for configuration.

This github issue can be considered a feature request.

**Comment by SebastianBoe** [comment]
Ah, I see ... you need to know the configuration values before boilerplate.cmake, so it is not straightforward to use Kconfig here ...

Hmm, I wonder how this can be resolved cleanly ...

**Comment by SebastianBoe** [comment]
Actually, I suspect that it is possible to get rid of the code that is using these variables so this issue can be resolved cleanly ...

**Comment by mbolivar** [comment]
> Actually, I suspect that it is possible to get rid of the code that is using these variables so this issue can be resolved cleanly ...

Any suggestions? These are a direct port from environment variables used by the the old Makefile, which predated the addition of the MCUBoot application-specific Kconfig options.

**Comment by SebastianBoe** [comment]
Re-opening as it seems to be possible to do this. See #189
