### ISSUE TITLE
The build fails when CMake is invoked from outside of the build directory

### ISSUE THREAD

**Issue by SebastianBoe** [runtimeco/mcuboot#187]
Hi,

I am observing that 

`mkdir build && cd build && cmake ..`

works.

But 

`cmake -Bbuild -H.`

doesn't for mcuboot/boot/zephyr

**Comment by SebastianBoe** [comment]
This patch might resolve the issue:

```
 # This is necessary to ensure mcuboot is linked into, and fits inside,
 # the boot partition.
-set(DTC_OVERLAY_FILE dts.overlay)
+set(DTC_OVERLAY_FILE ${CMAKE_CURRENT_LIST_DIR}/dts.overlay)

```

**Comment by mbolivar** [comment]
Though the `-B` option and using `-H<path>` are not officially supported  by CMake, it seems fine to add this patch to enable that workflow.

Want to propose a PR?

**Comment by SebastianBoe** [comment]
> Want to propose a PR?

Done
