### ISSUE TITLE
Add support for Intel Hex (.hex) in imgtool.py

### ISSUE THREAD

**Issue by utzig** [runtimeco/mcuboot#199]
The Intel Hex format (.hex) is very convenient for MCUboot since it includes the addresses at which the code is to be flashed. 

If imgtool.py supported .hex alongside with .bin, it would make it very simple to work with certain platforms that support flashing .hex files.

**Comment by carlescufi** [comment]
This can be closed now

**Comment by utzig** [comment]
I think we could write "This fixes #199" or something like that in the PR to do it automatically.
