### ISSUE TITLE
Clean up Zephyr flash driver name after 1.11

### ISSUE THREAD

**Issue by mbolivar** [runtimeco/mcuboot#202]
The MCUboot define FLASH_DRIVER_NAME needs to be globally renamed to FLASH_DEV_NAME after Zephyr 1.11.

Further reading: https://github.com/runtimeco/mcuboot/pull/201

**Comment by d3zd3z** [comment]
Should we keep compatibility with more than just a single version of Zephyr? For example, if we wanted to be compatible with two versions, this would get cleaned up, maybe 1.12?

Or, are we willing to just always require the latest release of Zephyr for any given version of MCUboot?

**Comment by mbolivar** [comment]
My preference would be to stay on mainline at least until Zephyr LTS 1.12 is released. We can make efforts to maintain compatibility with 1.12 when that's out. Zephyr is just moving too quickly right now to try to stay in sync with multiple versions.
