### ISSUE TITLE
Replace mcuboot flash_map by zephyr flash_map module

### ISSUE THREAD

**Issue by aditihilbert** [runtimeco/mcuboot#211]
zephyr has now compatible flash _map module - should be us instead of mcuboot one. It will also help with serve external flash for zephyr targets.

**Comment by carlescufi** [comment]
@nvlsianpu could you take a look at this this week?

**Comment by nvlsianpu** [comment]
OK, will look at this.

**Comment by nvlsianpu** [comment]
Issue was resolved by #268.

**Comment by nvlsianpu** [comment]
@utzig Can you close this?
