### ISSUE TITLE
Design document needs to have better definition of boot states behavior

### ISSUE THREAD

**Issue by aditihilbert** [runtimeco/mcuboot#214]
After reviewing the last update to the design document, a lot of inconsistencies in behavior were found. The previous discussion can be seen here: 

https://github.com/runtimeco/mcuboot/pull/87 

The main point of the discussion is regarding to how boot states should behave, which given the importance of correctness in the aforementioned code, documentation needs to be clear and very well thought through for all possible states a boot can be in.
Options
------------------------------------

Marti Bolivar  added a comment - 04/Aug/17 2:47 PM
https://github.com/runtimeco/mcuboot/pull/104 

Some remaining work I see: 

- There is still an "important caveat" to describing things in 
  terms of swap states, which means it's not quite right. 

- It's strange to say that "none" is a swap state. 

- This doesn't provide a clean explanation for how mcuboot handles an 
  interrupted swap.

**Comment by mbolivar** [comment]
I still feel like some things aren't quite clear, but I don't have a concrete step forward at the moment so I am closing this. Can always reopen.
