### ISSUE TITLE
sign.sh is very out of date

### ISSUE THREAD

**Issue by d3zd3z** [runtimeco/mcuboot#245]
The `sign.sh` in the root directory still refers to the now removed zep2newt.py script. Either just remove this script entirely, or update it to be and example of how to sign. Given that `samples/zephyr/Makefile` shows how to sign on Zephyr, and `newt` takes care of it on MyNewt, it is probably best to just remove the file.

**Comment by utzig** [comment]
`docs/readme-zephyr.md` contains the sentence: `There is a sign.sh script that gives some examples of how to make these signatures.` This should probably be updated with an example showing the command line flags similar to what is currently used in `sign.sh` and then the `sign.sh` file can be removed.
