### ISSUE TITLE
Trailer size calculation in python is faulty

### ISSUE THREAD

**Issue by tamasban** [runtimeco/mcuboot#285]
In image.py:48 the trailer size calculation is faulty because it does not consider the required space for swap_size. Compare it with bootutil_misc.c:125  Also the hard coded value(128) refers to this define in the code:  BOOT_STATUS_MAX_ENTRIES

If this increased above 128, then this check might does not catch faulty cases.

**Comment by utzig** [comment]
You're correct. It's a bit unfortunate that we can't get this automatically but we really need to add a new parameter to allow users to pass in the data (defaulting to 128).
