### ISSUE TITLE
Mcuboot-master location

### ISSUE THREAD

**Issue by Setec-intern** [runtimeco/mcuboot#305]
Hi, I am new to Zephyr. where should i copy the mcuboot-master folder after downloading.

**Comment by carlescufi** [comment]
@Setec-intern you don't need to copy anything, just clone zephyr and mcuboot side-by-side and, in the zephyr tree, `source zephyr-env.sh`

**Comment by d3zd3z** [comment]
@Setec-intern does this address your concern, or should this issue be extended to enhance the documentation?

**Comment by Setec-intern** [comment]
Thanks @carlescufi @d3zd3z I got it working.
